config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :pokemons, only: [:index, :edit, :show, :new, :create, :update]
  resources :teams, only: [:index, :edit, :show, :new, :create, :update]
  resources :trainers, only: [:index, :edit, :show, :new, :create, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :team
    #belongs_to :user
    #validates_associated :team
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :trainer
    has_many :pokemon
    #validates_length_of :pokemon, maximum: 6
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :teams
    #has_many :pokemon, :through => :teams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
        @pokemons = Pokemon.all
    end

    def show
        @pokemon = Pokemon.find(params[:id])
        pokemon_data = unique_url(@pokemon.pokedex_id)
        @pokemon_image = pokemon_data["sprites"]["front_default"]
        @pokemon_name = pokemon_data["species"]["name"]
        @pokemon_type = pokemon_data["types"][0]["type"]["name"]
        @pokemon_ability = pokemon_data["abilities"][0]["ability"]["name"]
    end

    def new
        @pokemon = Pokemon.new
    end

    def create
        @pokemon = Pokemon.new
        @pokemon.name = params[:name]
        @pokemon.team_id = params[:team_id]
        @pokemon.trainer_id = params[:trainer_id]
        @pokemon.pokedex_id = params[:pokedex_id]

        pokemon_data = unique_url(params[:pokedex_id])


        @pokemon.save
        redirect_to pokemon_path(@pokemon)
    end

    def edit
        @pokemon = Pokemon.find(params[:id])
    end

    def update
        @pokemon = Pokemon.find(params[:id])
        @pokemon.update(name: params[:pokemon][:name], trainer_id: params[:pokemon][:trainer_id], trainer_id: params[:pokemon][:trainer_id], pokedex_id: params[:pokemon][:pokedex_id])
        redirect_to pokemon_path(@pokemon)
    end

    private

        API_URL = 'https://pokeapi.co/api/v2/pokemon/'

        def unique_url(pokemon_number)
            response = HTTParty.get("#{API_URL}#{pokemon_number}")
            # TODO more error checking (500 error, etc)
            json = JSON.parse(response.body)
        end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

    def index
        @teams = Team.all
    end

    def show
        @team = Team.find(params[:id])
    end

    def new
        @team = Team.new
    end

    def create
        @team = Team.new
        @team.name = params[:name]
        @team.trainer_id = params[:trainer_id]
        @team.save
        redirect_to team_path(@team)
    end

    def edit
        @team = Team.find(params[:id])
    end

    def update
        @team = Team.find(params[:id])
        @team.update(name: params[:team][:name], trainer_id: params[:team][:trainer_id])
        redirect_to team_path(@team)
    end

    
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    def index
        @trainers = Trainer.all
    end

    def show
        @trainer = Trainer.find(params[:id])
    end

    def new
        @trainer = Trainer.new
    end

    def create
        @trainer = Trainer.new
        @trainer.name = params[:name]
        @trainer.save
        redirect_to trainer_path(@trainer)
    end

    def edit
        @trainer = Trainer.find(params[:id])
    end

    def update
        @trainer = Trainer.find(params[:id])
        @trainer.update(name: params[:trainer][:name])
        redirect_to trainer_path(@trainer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonMiniProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav_container">
      <div class="nav_category nav_logo">
        <%= link_to image_tag("logo.png"), "/" %>
      </div>
      <div class="nav_category trainer_hover">
        <%= (link_to "Show Trainers", trainers_path) %>
      </div>
      <div class="nav_category new_trainer_hover">
         <%= (link_to "New Trainer", new_trainer_path) %>
      </div>
      <div class="nav_category team_hover">
        <%= (link_to "New Team", new_team_path) %>
      </div>
      <div class="nav_category pokemon_hover">
        <%= (link_to "New Pokemon", new_pokemon_path) %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="index_image">
</div>

<div class="index_copy">
        <h1 class="index_title">Welcome to Pokemon Team Builder!</h1>
        <p class="index_body_copy">Pokemon Team Builder is an application that lets you create and save Pokemon teams for use in Pokemon Games.</p>
    </div>

app/views/pokemons/edit.html.erb
<div class="page_title">
    <h1 class="h1_title">
        Edit <%= @pokemon.name %>
    </h1>
</div>

<div class="page_content">

    <%= form_for @pokemon do |f| %>
    <div class="divider">
    <%= f.label 'Pokemon Name:', :class => "form_label" %><br>
    <%= f.text_field :name %><br>
    </div>
    <div class="divider">
    <%= f.label 'Pokedex ID:', :class => "form_label"  %><br>
    <%= f.text_field :pokedex_id %><br>
    </div>
    <div class="divider">
    <%= f.label 'Team ID:', :class => "form_label"  %><br>
    <%= f.text_field :team_id %><br>
    </div>
    <%= f.submit "Update Pokemon", :class => "button"  %>
    <% end %> 
</div>

app/views/pokemons/new.html.erb
<div class="page_title">
    <h1 class="h1_title">
        New Pokemon
    </h1>
</div>

<div class="page_content">

    <%= form_tag pokemons_path do %>

    <div class="divider">
    <label class="form_label">Pokemon Nickname:</label><br>
    <%= text_field_tag :name %><br>
    </div>

    <div class="divider">
    <label class="form_label">Team ID:</label><br>
    <%= text_field_tag :team_id %><br>
    </div>

    <div class="divider">
    <label class="form_label">Trainer ID:</label><br>
    <%= text_field_tag :trainer_id %><br>
    </div>

    <div class="divider">
    <label class="form_label">Pokedex ID:</label><br>
    <%= text_field_tag :pokedex_id git a%><br>
    </div>

    <%= submit_tag "Add Pokemon", :class => "button"  %>
    <% end %>
</div>

app/views/pokemons/show.html.erb
<div class="page_title">
    <h1 class="h1_title">
        <%= @pokemon.name %> <%= (link_to 'edit', edit_pokemon_path(@pokemon)) %>
    </h1>
</div>

<div class="page_content">

    <h1>Team: <%= @pokemon.team.name %> </h1>

    <img src="<%= @pokemon_image %>">

    <p>Name: <%= @pokemon_name %></p>
    <p>Type: <%= @pokemon_type %></p>
    <p>Ability: <%= @pokemon_ability %></p>

</div>

app/views/trainers/edit.html.erb
<div class="page_title">
    <h1 class="h1_title">
        Edit <%= @trainer.name %>
    </h1>
</div>

<div class="page_content">
    <%= form_for @trainer do |f| %>
    <div class="divider">
    <%= f.label 'Trainer Name:', :class => "form_label" %><br>
    <%= f.text_field :name %><br>
    </div>

    <%= f.submit "Update Trainer", :class => "button"  %>
    <% end %> 
</div>

app/views/trainers/index.html.erb
<div class="page_title">
    <h1 class="h1_title">
        View All Existing Trainers
    </h1>
</div>

<div class="page_content">
    <% @trainers.each do |trainer| %>
        <div style="text-align: center;">
            <span class="trainer_link_text"><%= (link_to trainer.name, trainer_path(trainer)) %></span> <span class="edit_link_text"><%= (link_to "edit", edit_trainer_path(trainer)) %>  </span> 
        </div>
    <% end %>
</div>

app/views/trainers/new.html.erb
<div class="page_title">
    <h1 class="h1_title">
        New Trainer
    </h1>
</div>

<div class="page_content">
    <%= form_tag trainers_path do %>
    <div class="divider">
    <label class="form_label">Trainer Name:</label><br>
    <%= text_field_tag :name%><br>
    </div>

    <%= submit_tag "Add Trainer", :class => "button" %>
    <% end %>
</div>

app/views/trainers/show.html.erb
<div class="page_title">
    <h1 class="h1_title">
        <%= @trainer.name %> ID: <%= @trainer.id %> <%= (link_to 'Edit', (edit_trainer_path(@trainer))) %>
    </h1>
</div>

<div class="page_content">
    <% @trainer.teams.each do |team| %>
        <div class="trainer_teams"><%= (link_to team.name, team_path(team)) %>  <%= (link_to "edit", edit_team_path(team)) %></div> 
        <div class="trainer_pokemon_preview">
            <% team.pokemon.each do |poke| %>
                <%= (link_to image_tag("https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/#{poke.pokedex_id}.png"), pokemon_path(poke)) %>
            <% end %>
        </div> 
    <% end %>
</div>